name: Re-Run Automation Container(when FAIL comes out)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Docker Container
        run: docker run --restart=on-failure ghcr.io/eoaud0012/my-automation-image:latest

